function distance = wrapper_metric_total_variation_square(dt, with_light, with_food,...
    departure_time, arrival_time, time_difference, meal_time_on_plane,...
    meal_ampl_on_plane)

[ampk_vec, lighting_per_max_vec, lighting_cry_max_vec,...
    lighting_rev_max_vec, lighting_ror_max_vec, per_vec, ...
    cry_vec, rev_vec, ror_vec, bmal_vec] = eating_circadian(dt, with_light, with_food,...
    departure_time, arrival_time, time_difference, meal_time_on_plane,...
    meal_ampl_on_plane);

[ampk_vec0, lighting_per_max_vec0, lighting_cry_max_vec0,...
    lighting_rev_max_vec0, lighting_ror_max_vec0, per_vec0, ...
    cry_vec0, rev_vec0, ror_vec0, bmal_vec0] = eating_circadian(dt, with_light, with_food,...
    0, 0, time_difference, meal_time_on_plane,...
    meal_ampl_on_plane);


integral_start = round(arrival_time/dt) + 1;
integral_end = round(600/dt);

distance = metric_total_variation_square(dt, cry_vec, cry_vec0, integral_start, integral_end);
end